version: '2'
services:
  nginx:
    scale: 1
    start_on_create: true
  phpfpm:
    scale: 1
    start_on_create: true
  phpfpm-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - hostname: ''
        priority: 1
        protocol: tcp
        service: phpfpm
        source_port: 9000
        target_port: 9000
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  mysql:
    scale: 1
    start_on_create: true
  nginx-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        service: nginx
        source_port: 85
        target_port: 80
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  redis:
    scale: 1
    start_on_create: true
